[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Actual Airtable credentials
  AIRTABLE_API_KEY = "patqy7ZJYDeMGRytK.c1b179191942edb6036729dd354759474477d71333d7031e70a2cc47c5b4e644"
  AIRTABLE_BASE_ID = "appMRsu00KNlqAg3A"
  NEXT_PUBLIC_AIRTABLE_API_KEY = "patqy7ZJYDeMGRytK.c1b179191942edb6036729dd354759474477d71333d7031e70a2cc47c5b4e644"
  NEXT_PUBLIC_AIRTABLE_BASE_ID = "appMRsu00KNlqAg3A"
  NEXT_PUBLIC_USE_MOCK_DATA = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes - redirect to Netlify Functions
[[redirects]]
  from = "/api/tasks"
  to = "/.netlify/functions/get-tasks"
  status = 200

[[redirects]]
  from = "/api/comments"
  to = "/.netlify/functions/get-comments"
  status = 200
  query = {taskId = ":taskId"}

[[redirects]]
  from = "/api/comments"
  to = "/.netlify/functions/add-comment"
  status = 200
  method = "POST"

[[redirects]]
  from = "/api/tasks"
  to = "/.netlify/functions/update-task"
  status = 200
  methods = ["PATCH", "PUT"]

[[redirects]]
  from = "/api/backlinks"
  to = "/.netlify/functions/get-backlinks"
  status = 200

[[redirects]]
  from = "/api/url-performance"
  to = "/.netlify/functions/get-url-performance"
  status = 200

[[redirects]]
  from = "/api/approvals"
  to = "/.netlify/functions/get-approvals"
  status = 200
  methods = ["GET"]

[[redirects]]
  from = "/api/approvals"
  to = "/.netlify/functions/update-approval"
  status = 200
  methods = ["POST", "PUT", "PATCH"]

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
