[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Updated Airtable credentials
  AIRTABLE_API_KEY = "patDzIkqPGxe1t5jl.fe3e6fa1c25d7438e70de845827f7dcfa8ffb3d14baf0e17bff380bca8459175"
  AIRTABLE_BASE_ID = "appUtQLunL1f05FrQ"
  NEXT_PUBLIC_AIRTABLE_API_KEY = "patDzIkqPGxe1t5jl.fe3e6fa1c25d7438e70de845827f7dcfa8ffb3d14baf0e17bff380bca8459175"
  NEXT_PUBLIC_AIRTABLE_BASE_ID = "appUtQLunL1f05FrQ"
  NEXT_PUBLIC_USE_MOCK_DATA = "false"
  # Disable the connection issues flag
  NEXT_PUBLIC_DISABLE_CONNECTION_ISSUES_FLAG = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes - redirect to Netlify Functions
[[redirects]]
  from = "/api/tasks"
  to = "/.netlify/functions/get-tasks"
  status = 200

[[redirects]]
  from = "/api/comments"
  to = "/.netlify/functions/get-comments"
  status = 200
  query = {taskId = ":taskId"}

[[redirects]]
  from = "/api/comments"
  to = "/.netlify/functions/add-comment"
  status = 200
  method = "POST"

[[redirects]]
  from = "/api/tasks"
  to = "/.netlify/functions/update-task"
  status = 200
  methods = ["PATCH", "PUT"]

[[redirects]]
  from = "/api/backlinks"
  to = "/.netlify/functions/get-backlinks"
  status = 200

[[redirects]]
  from = "/api/url-performance"
  to = "/.netlify/functions/get-url-performance"
  status = 200

[[redirects]]
  from = "/api/approvals"
  to = "/.netlify/functions/get-approvals"
  status = 200
  methods = ["GET"]

[[redirects]]
  from = "/api/approvals"
  to = "/.netlify/functions/update-approval"
  status = 200
  methods = ["POST", "PUT", "PATCH"]

[[redirects]]
  from = "/api/debug-env"
  to = "/.netlify/functions/debug-env"
  status = 200

[[redirects]]
  from = "/api/clients"
  to = "/.netlify/functions/get-clients"
  status = 200

[[redirects]]
  from = "/api/months"
  to = "/.netlify/functions/get-available-months"
  status = 200

[[redirects]]
  from = "/api/conversation-history"
  to = "/.netlify/functions/get-conversation-history"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
